version: '3'
services:
  db:
    image: mongo:latest
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 5000:5000

  ui:
    build: ./ui
    ports:
      - 3000:3000

volumes:
  mongodbdata:
